Universidade Federal do ABC (UFABC)  
Curso: Bacharelado em Ciências Econômicas  
Disciplina: Economia Matemática  
Período: 2º Quadrimestre de 2026  
Turmas: Matutino (DA2ESHC027-21SB) e Noturno (NA2ESHC027-21SB)  
Prova 01: sistemas lineares, matrizes e determinantes (Aulas 2 a 11) | Entrega: 24 de julho de 2026 (sexta-feira) 
  
Prof. Dr. Elson Rodrigo de Souza Santos  
WhatsApp: (41) 9 8454 0549 | E-mail: elson129@gmail.com ou elson.rodrigo@ufabc.edu.br | Repositório: github.com/elsonr29  
18 de julho de 2026  

RESOLUÇÃO DA PROVA 01

Observações:
    
1) Utilizamos o Python e os fundamentos da "quantitative economics", aula 8 - Linear Equations and Matrix Algebra < https://intro.quantecon.org/linear_equations.html > ;   
2) Os resultados devem ser coerentes com os obtidos manualmente; 
3) O Python é uma forma inclusiva de demonstrar os conceitos e modelos apresentados e discutidos em sala de aula;  
4) A ênfase é a parte quantitativa da Prova 01. 

RESOLUÇÃO

Seguimos a ordem de resolução das variantes das provas:

1) Prova01_alpha (noturno)
2) Prova02_beta (matutino)
3) Prova03_tau (substitutiva)

As provas possuem níveis de dificuldades similares. A diferença consiste nos sistemas lineares e na nature dos choques exógenos.

In [1]:
# Pacotes

# Instação (se necessário)

!pip install numpy sympy

#Obs.: Utilizamos o numpy para manipulação de matrizes e álgebra e o matplotlib para formatação de gráficos. Seguimos o caminho proposto pela Quantitative Economics.

Defaulting to user installation because normal site-packages is not writeable


In [2]:
# Carregamento

import numpy as np  
import sympy as sp

# Obs.: após o carregamento é possível resolver a lista.

**Prova01_alpha (noturno)**


Considere o sistema de equações lineares abaixo e responda:

$$
\begin{cases}
    2x_1 + 3x_2 - x_3 = -2 \\
    4x_1 + x_2 + 2x_3 = 13 \\
    -x_1 + 2x_2 + 3x_3 = 5
\end{cases}
$$

**1)** Apresente o sistema de equações lineares no formato matricial $Ax=d$. Em seguida, calcule o determinante por meio da **expansão de Laplace** e discuta a existência de uma solução única e determinada para o sistema.

**2)** Obtenha a matriz inversa $A^{-1}$, considerando que $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$.

**3)** Quais são os componentes do vetor $x$? Utilize a regra de Cramer e demonstre que essa é a solução única do sistema.

**4)** Suponha que o sistema de equações lineares original represente um modelo econômico estrutural. Diante de um choque exógeno que altera as relações lineares, o modelo passa a responder à nova configuração:

$$
\begin{cases}
    2x_1 + 3x_2 - x_3 = -2 \\
    4x_1 + x_2 + 2x_3 = 13 \\
    4x_1 + 6x_2 - 2x_3 = -10
\end{cases}
$$

Esse sistema possui solução única? Justifique e demonstre por meio do determinante $\vert{}A\vert{}$ e das implicações na relação $x = A^{-1}d$.

**Obs.:** Responda às discussões teóricas com o devido rigor matemático e apresente detalhadamente o passo a passo para a resolução dos modelos formais.

**RESOLUÇÃO - Prova01_alpha**

**Questão 1)** Apresente o sistema de equações lineares no formato matricial $Ax=d$. Em seguida, calcule o determinante por meio da **expansão de Laplace** e discuta a existência de uma solução única e determinada para o sistema. Assim, temos:

a) Transformamos o sistema linear para o formato matricial $Ax=d$;

b) Detercinante da matriz A pela expansão de Laplace;

c) Verificar se há solução.



In [3]:
# carregar pacotes

import numpy as np
import sympy as sp

a) Transformamos o sistema linear para o formato matricial $Ax=d$.

Esta representação indica informações relevantes:
* A existência de dependência linear entre as linhas ($L_1$, $L_2$ e $L_3$) ou colunas ($C_1$, $C_2$ e $C_3$) da matriz $A$;
* A consistência do vetor $d$, o que sugere a existência de pelo menos uma solução possível;
* A equivalência entre o número de equações e o de variáveis (posto completo ou *full rank*), indicativo para a existência de uma solução única;
* A confirmação de que $|A| \neq 0$, requisito obrigatório para que a solução seja única.

In [4]:
import numpy as np

# 1. Matriz de coeficientes (A)
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-1, 2, 3]
])

# 2. Vetor de variáveis (x)
x = np.array([['x1'], ['x2'], ['x3']]) 

# 3. Vetor de constantes (d)
d = np.array([[-2], [13], [5]]) 

print("Matriz A:")
print(A)

print("\nVetor x:")
print(x)

print("\nVetor d:")
print(d)

Matriz A:
[[ 2  3 -1]
 [ 4  1  2]
 [-1  2  3]]

Vetor x:
[['x1']
 ['x2']
 ['x3']]

Vetor d:
[[-2]
 [13]
 [ 5]]


b) Determinante da matriz A pela expansão de Laplace

Assim, temos:

* Podemos calcular o determinante por intermédio de qualquer linha ou coluna da matriz $A$;
* O passo fundamental consiste em identificar o cofator $C_{ij}$, a matriz menor $M_{ij}$ e o respectivo sinal (dado por $(-1)^{i+j}$).

Fórmulas:

* Matriz Menor $(M_{ij})$

A matriz menor $M_{ij}$ é definida como o determinante da submatriz que sobra quando eliminamos a linha $i$ e a coluna $j$ da matriz original $A$.

$$
M_{11} = \begin{vmatrix} 
a_{22} & a_{23} \\ 
a_{32} & a_{33} 
\end{vmatrix} = (a_{22} \cdot a_{33}) - (a_{23} \cdot a_{32})
$$

* Cofator $(C_{ij})$

O cofator ajusta o sinal da matriz menor com base na posição do elemento na matriz original. A fórmula completa é:

$$C_{ij} = (-1)^{i+j} M_{ij}$$

* Determinante pela Expansão de Laplace

O determinante de uma matriz $A$ de ordem $n \times n$ pode ser calculado escolhendo qualquer linha fixa $i$ ou qualquer coluna fixa $j$. A fórmula consiste em multiplicar os elementos da linha (ou coluna) escolhida pelos seus respectivos cofatores e somar os resultados.

Expansão ao longo de uma linha fixa $i$:

$$|A| = \sum_{j=1}^{n} a_{ij} C_{ij} = a_{i1}C_{i1} + a_{i2}C_{i2} + \dots + a_{in}C_{in}$$

Expansão ao longo de uma coluna fixa $j$:

$$|A| = \sum_{i=1}^{n} a_{ij} C_{ij} = a_{1j}C_{1j} + a_{2j}C_{2j} + \dots + a_{nj}C_{nj}$$

Onde:
* $a_{ij}$ é o elemento da matriz localizado na linha $i$ e coluna $j$;
* $C_{ij}$ é o cofator correspondente ao elemento $a_{ij}$.



In [5]:
# b) Determinante da matriz A pela expansão de Laplace

# usamos a expansão da primeira linha

import numpy as np

# 1. Definindo a matriz de coeficientes (A)
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-1, 2, 3]
])

# Inicializando a variável para armazenar o determinante total
det_A = 0

# Fixando a primeira linha ( índice no Python começa em 0)
i = 0

print("Cálculo do determinante pela expansão de Laplace (Primeira Linha):\n")

# 2. Colunas da primeira linha
for j in range(A.shape[1]):
    
    # Identificando o elemento a_ij
    a_ij = A[i, j]
    
    # 3. Criando a submatriz para calcular o menor M_ij
    # np.delete remove a linha 'i' (axis=0) e a coluna 'j' (axis=1)
    submatriz = np.delete(np.delete(A, i, axis=0), j, axis=1)
    
    # Calculando o valor do menor M_ij (determinante da submatriz 2x2)
    # Utilizamos round() para evitar pequenos erros de arredondamento de ponto flutuante do numpy
    M_ij = round(np.linalg.det(submatriz))
    
    # 4. Calculando o cofator C_ij
    C_ij = ((-1) ** (i + j)) * M_ij
    
    # Multiplicando o elemento pelo seu cofator e somando ao total
    termo = a_ij * C_ij
    det_A += termo
    
    # Imprimindo o passo a passo para cada elemento
    print(f"--- Elemento a_{i+1}{j+1} = {a_ij} ---")
    print(f"Submatriz para M_{i+1}{j+1}:\n{submatriz}")
    print(f"Menor M_{i+1}{j+1} = {M_ij}")
    print(f"Cofator C_{i+1}{j+1} = (-1)^{i+1+j+1} * {M_ij} = {C_ij}")
    print(f"Termo da soma = {a_ij} * {C_ij} = {termo}\n")

# 5. Resultado Final
print(f"====================================")
print(f"Determinante total (|A|) = {det_A}")
print(f"====================================")


Cálculo do determinante pela expansão de Laplace (Primeira Linha):

--- Elemento a_11 = 2 ---
Submatriz para M_11:
[[1 2]
 [2 3]]
Menor M_11 = -1
Cofator C_11 = (-1)^2 * -1 = -1
Termo da soma = 2 * -1 = -2

--- Elemento a_12 = 3 ---
Submatriz para M_12:
[[ 4  2]
 [-1  3]]
Menor M_12 = 14
Cofator C_12 = (-1)^3 * 14 = -14
Termo da soma = 3 * -14 = -42

--- Elemento a_13 = -1 ---
Submatriz para M_13:
[[ 4  1]
 [-1  2]]
Menor M_13 = 9
Cofator C_13 = (-1)^4 * 9 = 9
Termo da soma = -1 * 9 = -9

Determinante total (|A|) = -53


C) Verificar se há solução

O determinante da matriz de coeficientes resulta em $|A| = -53$. Logo, o sistema de equações lineares no formato $Ax = d$ possui uma solução única e determinada. A fundamentação é que a determinante ser diferente de zero ($|A| \neq 0$).

O resultado $|A| = -53 \neq 0$ comprova matematicamente que a matriz apresenta posto completo (*full rank*) e não possui dependência linear entre as suas linhas ou colunas. Deste modo, existe um único vetor $x$ capaz de satisfazer todas as três equações simultaneamente.

Adicionalmente, demonstramos que a multiplicação da matriz $A$ pela sua inversa resulta igual à matriz identidade.

In [6]:
# c) verificar se há solução

import numpy as np

# Observação: O código assume que a matriz 'A' e a variável 'det_A' já foram definidas nas células anteriores.

print("=== Análise do Sistema ===")

if det_A != 0:
    print(f"O determinante resulta diferente de zero (|A| = {det_A}).")
    print("Conclusão: A matriz é não singular e o sistema possui solução única\n")
    
    print("=== Demonstração: A * A^(-1) = I ===")
    
    # 1. Calculando a matriz inversa de A
    A_inv = np.linalg.inv(A)
    
    # 2. Multiplicando A pela sua inversa
    # A função np.round limpa os resíduos de ponto flutuante para a exibição ficar exata
    identidade_calculada = np.round(A @ A_inv)
    
    print("Resultado da multiplicação (A @ A_inv):")
    print(identidade_calculada)
    
    # 3. Verificação lógica do sistema
    identidade_real = np.eye(A.shape[0])
    
    # np.allclose verifica se as matrizes são iguais considerando a precisão decimal
    if np.allclose(A @ A_inv, identidade_real):
        print("\nConfirmado!")
        
else:
    print("O determinante resulta igual a zero (|A| = 0).")
    print("Conclusão: A matriz é singular. O sistema é impossível ou possui infinitas soluções.")

=== Análise do Sistema ===
O determinante resulta diferente de zero (|A| = -53).
Conclusão: A matriz é não singular e o sistema possui solução única

=== Demonstração: A * A^(-1) = I ===
Resultado da multiplicação (A @ A_inv):
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

Confirmado!


**Questão 2)** Obtenha a matriz inversa $A^{-1}$, considerando que $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$.

Como sabemos que a matriz inversa existe, calculamos a matriz correspondente a partir da fórmula acima. Assim, estabelecemos como roteiro:

a) Cálculo da matriz de cofatores ($C$);

b) Obtenção da matriz adjunta ($\operatorname{adj} A$), a qual corresponde à transposta da matriz de cofatores ($C^T$);

c) Matriz inversa a partir da fórmula: $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$;

d) Prova $A A^{-1} = I$.

In [7]:
# carregar pacotes

import numpy as np
import sympy as sp

a) Cálculo da matriz de cofatores ($C$)

A matriz de cofatores $C$ é obtida pela aplicação da fórmula $C_{ij}$ para cada elemento da matriz $A$. A fórmula algébrica correspondente é:

$$C_{ij} = (-1)^{i+j} M_{ij}$$

Dessa forma, obtemos a seguinte matriz estruturada:

$$
C = \begin{bmatrix} 
C_{11} & C_{12} & C_{13} \\ 
C_{21} & C_{22} & C_{23} \\ 
C_{31} & C_{32} & C_{33} 
\end{bmatrix}
$$


In [8]:
# a) Cálculo da matriz de cofatores C

# Definindo a matriz A original do problema
A_np = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-1, 2, 3]
])

n = A_np.shape[0]
C_np = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        # Remove a linha i e a coluna j para obter a submatriz
        submatrix = np.delete(np.delete(A_np, i, axis=0), j, axis=1)
        
        # Menor principal M_ij
        minor_det = int(round(np.linalg.det(submatrix)))
        
        # Cofator C_ij = (-1)^(i+j) * M_ij
        C_np[i, j] = ((-1) ** (i + j)) * minor_det

print("a) Matriz de Cofatores C:")
print(C_np)


a) Matriz de Cofatores C:
[[ -1 -14   9]
 [-11   5  -7]
 [  7  -8 -10]]


b) Obtenção da matriz adjunta ($\operatorname{adj} A$), a qual corresponde à transposta da matriz de cofatores ($C^T$)

Aplicamos a transposição entre linhas e colunas


In [9]:
# b) Obtenção da matriz adjunta A, a qual corresponde à transposta da matriz de cofatores de C

# Calculando a Matriz Adjunta (transposta da matriz de cofatores)
adj_A_np = C_np.T

print("b) Matriz Adjunta adj(A) = C^T:")
print(adj_A_np)

b) Matriz Adjunta adj(A) = C^T:
[[ -1 -11   7]
 [-14   5  -8]
 [  9  -7 -10]]


c) Matriz inversa a partir da fórmula: $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$

In [10]:
# c) Matriz inversa

# 1. Conversão da matriz numérica para o formato simbólico
adj_A_sym = sp.Matrix(adj_A_np)

# 2. Aplicação da fórmula analítica
# A função sp.Integer preserva o rigor matemático e gera frações em vez de decimais
A_inv_sym = (1 / sp.Integer(det_A)) * adj_A_sym

# 3. Impressão estruturada do resultado
print("c) Matriz Inversa A^(-1):")
sp.pprint(A_inv_sym)

c) Matriz Inversa A^(-1):
⎡        11         ⎤
⎢1/53    ──    -7/53⎥
⎢        53         ⎥
⎢                   ⎥
⎢ 14                ⎥
⎢ ──    -5/53  8/53 ⎥
⎢ 53                ⎥
⎢                   ⎥
⎢               10  ⎥
⎢-9/53  7/53    ──  ⎥
⎣               53  ⎦


d) Prova $A A^{-1} = I$

In [11]:
# d) Prova que A * A⁽-1) = I

A_sym = sp.Matrix(A_np)

print("d) Prova: A * A^(-1) = I:")

sp.pprint(
    sp.Eq(
        sp.MatMul(A_sym, A_inv_sym, evaluate=False),
        A_sym * A_inv_sym
    )
)

print("\n" + "-" * 50)

# Obs. automatizamos o processo pelos pacotes

d) Prova: A * A^(-1) = I:
            ⎡        11         ⎤            
            ⎢1/53    ──    -7/53⎥            
            ⎢        53         ⎥            
⎡2   3  -1⎤ ⎢                   ⎥   ⎡1  0  0⎤
⎢         ⎥ ⎢ 14                ⎥   ⎢       ⎥
⎢4   1  2 ⎥⋅⎢ ──    -5/53  8/53 ⎥ = ⎢0  1  0⎥
⎢         ⎥ ⎢ 53                ⎥   ⎢       ⎥
⎣-1  2  3 ⎦ ⎢                   ⎥   ⎣0  0  1⎦
            ⎢               10  ⎥            
            ⎢-9/53  7/53    ──  ⎥            
            ⎣               53  ⎦            

--------------------------------------------------


**Questão 3)** Quais são os componentes do vetor $x$? Utilize a regra de Cramer e demonstre que essa é a solução única do sistema

Seguimos o roteiro:

a) Calculamos os determinantes $|A|$, $|A_1|$, $|A_2|$ e $|A_3|$;

b) Aplicação da regra de Cramer para obter o vetor de soluções $x$;

c) Provamos que a solução é única por meio da substituição no sistema de equações lineares e na matriz $Ax=d$.

Obs.: sabemos que existe solução única e determinada devido ao determinante $|A| \neq 0$.


In [12]:
# Carregar pacotes

import numpy as np
import sympy as sp

a) Calculamos os determinantes $|A|$, $|A_1|$, $|A_2|$ e $|A_3|$

Para uma matriz genérica $3 \times 3$ definida como:

$$
A = \begin{bmatrix} 
a_{11} & a_{12} & a_{13} \\ 
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} 
\end{bmatrix}
$$

A fórmula algébrica direta para calcular o determinante original $|A|$ resulta em:

$$|A| = (a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32}) - (a_{13}a_{22}a_{31} + a_{11}a_{23}a_{32} + a_{12}a_{21}a_{33})$$

Para obter os determinantes modificados ($|A_1|$, $|A_2|$ e $|A_3|$), nós substituímos a coluna correspondente pelo vetor de termos independentes $d$:

$$
d = \begin{bmatrix} 
d_1 \\ 
d_2 \\ 
d_3 
\end{bmatrix}
$$

*   **Para $|A_1|$:** Substituímos a primeira coluna de $A$ por $d$ e aplicamos a mesma fórmula de cálculo:
$$
|A_1| = \begin{vmatrix} 
d_1 & a_{12} & a_{13} \\ 
d_2 & a_{22} & a_{23} \\ 
d_3 & a_{32} & a_{33} 
\end{vmatrix}
$$

*   **Para $|A_2|$:** Substituímos a segunda coluna de $A$ por $d$:
$$
|A_2| = \begin{vmatrix} 
a_{11} & d_1 & a_{13} \\ 
a_{21} & d_2 & a_{23} \\ 
a_{31} & d_3 & a_{33} 
\end{vmatrix}
$$

*   **Para $|A_3|$:** Substituímos a terceira coluna de $A$ por $d$:
$$
|A_3| = \begin{vmatrix} 
a_{11} & a_{12} & d_1 \\ 
a_{21} & a_{22} & d_2 \\ 
a_{31} & a_{32} & d_3 
\end{vmatrix}
$$

Agora, aplicamos para encontrar a solução do sistema linear

In [13]:
# a) calculamos os determinantes

# 1. Definindo a matriz de coeficientes A e o vetor de termos independentes d
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-1, 2, 3]
])

d = np.array([-2, 13, 5])

print("Matriz Original A:")
print(A)
print("Determinante |A| = ", round(np.linalg.det(A)))
print("*" * 30)

# 2. Construindo A1 (substituindo a primeira coluna por d)
A1 = A.copy()
A1[:, 0] = d

print("\nMatriz A1:")
print(A1)
print("Determinante |A1| = ", round(np.linalg.det(A1)))
print("*" * 30)

# 3. Construindo A2 (substituindo a segunda coluna por d)
A2 = A.copy()
A2[:, 1] = d

print("\nMatriz A2:")
print(A2)
print("Determinante |A2| = ", round(np.linalg.det(A2)))
print("*" * 30)

# 4. Construindo A3 (substituindo a terceira coluna por d)
A3 = A.copy()
A3[:, 2] = d

print("\nMatriz A3:")
print(A3)
print("Determinante |A3| = ", round(np.linalg.det(A3)))
print("*" * 30)




Matriz Original A:
[[ 2  3 -1]
 [ 4  1  2]
 [-1  2  3]]
Determinante |A| =  -53
******************************

Matriz A1:
[[-2  3 -1]
 [13  1  2]
 [ 5  2  3]]
Determinante |A1| =  -106
******************************

Matriz A2:
[[ 2 -2 -1]
 [ 4 13  2]
 [-1  5  3]]
Determinante |A2| =  53
******************************

Matriz A3:
[[ 2  3 -2]
 [ 4  1 13]
 [-1  2  5]]
Determinante |A3| =  -159
******************************


b) Aplicação da regra de Cramer para obter o vetor de soluções $x$

A regra de Cramer estabelece que cada variável do sistema linear resulta da razão entre o determinante da matriz modificada correspondente e o determinante da matriz original de coeficientes. A aplicação algébrica segue a estrutura abaixo:

Para o componente $x_1$:
$$x_1 = \frac{|A_1|}{|A|}$$

Para o componente $x_2$:
$$x_2 = \frac{|A_2|}{|A|}$$

Para o componente $x_3$:
$$x_3 = \frac{|A_3|}{|A|}$$

Ao final do processo analítico, nós organizamos os termos obtidos para compor formalmente o vetor de soluções $x$:

$$
x = \begin{bmatrix} 
x_1 \\ 
x_2 \\ 
x_3 
\end{bmatrix}
=
\begin{bmatrix} 
\frac{|A_1|}{|A|} \\ 
\frac{|A_2|}{|A|} \\ 
\frac{|A_3|}{|A|} 
\end{bmatrix}
$$

Aplicação da Regra de Cramer para encontrar o vetor de variáveis x


In [14]:
# b) Aplicação da regra de Cramer

# 1. Cálculo dos determinantes exatos
det_A = round(np.linalg.det(A))
det_A1 = round(np.linalg.det(A1))
det_A2 = round(np.linalg.det(A2))
det_A3 = round(np.linalg.det(A3))

# 2. Aplicação da Regra de Cramer para obter os componentes
x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A

# 3. Estruturação do vetor de soluções x
x = np.array([x1, x2, x3], dtype=int)

print("=== Aplicação da Regra de Cramer ===")
print(f"Componente x_1 = {det_A1} / {det_A} = {x1}")
print(f"Componente x_2 = {det_A2} / {det_A} = {x2}")
print(f"Componente x_3 = {det_A3} / {det_A} = {x3}\n")

print("Vetor de soluções x:")
print(x)


=== Aplicação da Regra de Cramer ===
Componente x_1 = -106 / -53 = 2.0
Componente x_2 = 53 / -53 = -1.0
Componente x_3 = -159 / -53 = 3.0

Vetor de soluções x:
[ 2 -1  3]


c) Provamos que a solução é única por meio da substituição no sistema de equações lineares e na matriz $Ax=d$.

In [15]:
# c) prova

A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-1, 2, 3]
])
d = np.array([-2, 13, 5])
x = np.array([2, -1, 3])

print("=== 1. Prova por substituição no sistema de equações lineares ===")

# Substituição manual em cada linha do sistema
eq1 = 2*x[0] + 3*x[1] - 1*x[2]
eq2 = 4*x[0] + 1*x[1] + 2*x[2]
eq3 = -1*x[0] + 2*x[1] + 3*x[2]

print(f"Equação 1: 2(2) + 3(-1) - 1(3) = {eq1} (Resultado esperado: {d[0]})")
print(f"Equação 2: 4(2) + 1(-1) + 2(3) = {eq2} (Resultado esperado: {d[1]})")
print(f"Equação 3: -1(2) + 2(-1) + 3(3) = {eq3} (Resultado esperado: {d[2]})\n")

print("=== 2. Prova por substituição na forma matricial Ax = d ===")

# Multiplicação da matriz A pelo vetor x
d_calculado = A @ x

print("Resultado do produto matricial A @ x:")
print(d_calculado)
print("Vetor de constantes d original:")
print(d)

# Verificação lógica de igualdade
if np.array_equal(d_calculado, d):
    print("\nConclusão final: A igualdade Ax = d é verdadeira.")
    print("Prova que o vetor x representa a solução única do modelo.")
else:
    print("\nConclusão final: A igualdade não foi satisfeita.")


=== 1. Prova por substituição no sistema de equações lineares ===
Equação 1: 2(2) + 3(-1) - 1(3) = -2 (Resultado esperado: -2)
Equação 2: 4(2) + 1(-1) + 2(3) = 13 (Resultado esperado: 13)
Equação 3: -1(2) + 2(-1) + 3(3) = 5 (Resultado esperado: 5)

=== 2. Prova por substituição na forma matricial Ax = d ===
Resultado do produto matricial A @ x:
[-2 13  5]
Vetor de constantes d original:
[-2 13  5]

Conclusão final: A igualdade Ax = d é verdadeira.
Prova que o vetor x representa a solução única do modelo.


**Questão 4)** Suponha que o sistema de equações lineares original represente um modelo econômico estrutural. Diante de um choque exógeno que altera as relações lineares, o modelo passa a responder à nova configuração:

$$
\begin{cases}
    2x_1 + 3x_2 - x_3 = -2 \\
    4x_1 + x_2 + 2x_3 = 13 \\
    4x_1 + 6x_2 - 2x_3 = -10
\end{cases}
$$

Esse sistema possui solução única? Justifique e demonstre por meio do determinante $\vert{}A\vert{}$ e das implicações na relação $x = A^{-1}d$.

Seguimos o roteiro:

a) Analisar se existe dependência linear; 

b) Identificar formalmente pelo determinante $|A|$;

c) Implicações

In [16]:
# Carregar pacotes

import numpy as np
import sympy as sp

a) Analisar se existe dependência linear

Na análise de um sistema linear por meio da sua representação matricial ($Ax = d$), o objetivo é avaliar a existência de dependência linear entre as linhas ou colunas. Dessa forma, identificar se existe independência linear pela condição de posto completo (*full rank*) da matriz de coeficientes $A$.

In [17]:
# a) Analisar se existe dependência linear

# 1. Definição da matriz de coeficientes (A) e do vetor de termos independentes (d)
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [4, 6, -2]
])
d = np.array([-2, 13, -10])

print("=== Análise de Dependência Linear ===")

# 2. Cálculo do Determinante
# Um determinante igual a zero indica que a matriz não possui posto completo
det_A = np.linalg.det(A)
# Utilizamos round para eliminar ruídos de ponto flutuante do NumPy
det_A_arredondado = round(det_A)
print(f"Determinante da matriz A: {det_A_arredondado}")

# 3. Verificação do Posto (Rank) da matriz
# O posto indica o número máximo de linhas ou colunas linearmente independentes
posto_A = np.linalg.matrix_rank(A)
numero_variaveis = A.shape[1]

print(f"Posto da matriz A: {posto_A}")
print(f"Número de variáveis no modelo: {numero_variaveis}")

# 4. Conclusão lógica baseada no posto
if posto_A < numero_variaveis:
    print("\nConclusão: O sistema apresenta dependência linear.")
    print("A matriz é singular e não possui posto completo (not full rank).")
    
    # Verificação adicional pelo Teorema de Rouché-Capelli
    # Criamos a matriz aumentada [A | d] para verificar a consistência do modelo
    matriz_aumentada = np.column_stack((A, d))
    posto_aumentada = np.linalg.matrix_rank(matriz_aumentada)
    
    if posto_A == posto_aumentada:
        print("Diagnóstico final: O sistema possui infinitas soluções (sistema possível e indeterminado).")
    else:
        print("Diagnóstico final: O sistema não possui solução (sistema impossível).")

else:
    print("\nConclusão: Não existe dependência linear.")
    print("A matriz possui posto completo (full rank) e o sistema admite solução única.")

=== Análise de Dependência Linear ===
Determinante da matriz A: 0
Posto da matriz A: 2
Número de variáveis no modelo: 3

Conclusão: O sistema apresenta dependência linear.
A matriz é singular e não possui posto completo (not full rank).
Diagnóstico final: O sistema não possui solução (sistema impossível).


b) Identificar formalmente pelo determinante $|A|$

Para formalizar a identificação de dependência linear, calculamos o determinante da matriz de coeficientes $A$. 

Se houver dependência linear entre as linhas ou colunas, o determinante resulta igual a zero ($|A| = 0$).


In [18]:
# b) Identificar formalmente pelo determinante

# 1. Definição da matriz de coeficientes (A) com base no sistema estrutural
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [4, 6, -2]
])

print("=== Análise do Determinante e Dependência Linear ===")

# 2. Cálculo do determinante da matriz
det_A = np.linalg.det(A)

print(f"Valor computacional do determinante: {det_A}")
print(f"Valor arredondado do determinante |A| = {round(det_A)}\n")

# 3. Teste de dependência linear (verificação se |A| = 0)
# A função isclose garante a precisão matemática contra erros de ponto flutuante
if np.isclose(det_A, 0):
    print("Conclusão: O determinante resulta igual a zero (|A| = 0).")
    print("Isso comprova que existe dependência linear entre as equações do modelo.")
    print("A matriz é singular e o sistema não possui uma solução única.")
else:
    print("Conclusão: O determinante é diferente de zero (|A| != 0).")
    print("Não existe dependência linear. O modelo possui posto completo (full rank) e solução única.")

=== Análise do Determinante e Dependência Linear ===
Valor computacional do determinante: 0.0
Valor arredondado do determinante |A| = 0

Conclusão: O determinante resulta igual a zero (|A| = 0).
Isso comprova que existe dependência linear entre as equações do modelo.
A matriz é singular e o sistema não possui uma solução única.


c) Implicações

Na relação matricial $x = A^{-1}d$, a existência do vetor de soluções $x$ depende obrigatoriamente do cálculo prévio da matriz inversa $A^{-1}$. 

A fórmula para a obtenção da matriz inversa é definida por:
$$A^{-1} = \frac{1}{|A|} \operatorname{adj} A$$

Quando o modelo apresenta dependência linear o determinante resulta em zero ($|A| = 0$). Essa restrição impõe uma divisão por zero que é uma operação indefinida (impossível).

Consequências estruturais para o modelo:

1. Matriz Singular: matriz de coeficientes $A$ não possui inversa;
2. Falha do Método: impossível aplicar a relação $x = A^{-1}d$ para encontrar os valores das variáveis;
3. Ausência de Solução Única:  modelo possui infinitas soluções ou de total ausência de solução.

In [19]:
# c) Implicações

# 1. Definição da matriz A (com dependência linear) e do vetor d
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [4, 6, -2]
])
d = np.array([-2, 13, -4])

print("=== Tentativa de resolução via x = A^(-1)d ===")

try:
    # 2. O algoritmo tenta calcular a matriz inversa A^(-1)
    print("Iniciando o cálculo da inversa de A (np.linalg.inv)...")
    A_inv = np.linalg.inv(A)
    
    # Se funcionar (o que não vai ocorrer neste caso), calcula x
    x = A_inv @ d
    print("Vetor de soluções encontrado:", x)

except np.linalg.LinAlgError as erro_sistema:
    # 3. O algoritmo captura a falha matemática (divisão por zero estrutural)
    print("\n[FALHA MATEMÁTICA DETECTADA]")
    print(f"Mensagem interna do Python: {erro_sistema}")
    print("\nInterpretação Econômica e Matemática:")
    print("O sistema bloqueou a operação porque a matriz A é singular (|A| = 0).")
    print("A dependência linear torna a matriz não inversível.")
    print("Consequentemente, é impossível calcular x = A^(-1)d para este modelo.")

=== Tentativa de resolução via x = A^(-1)d ===
Iniciando o cálculo da inversa de A (np.linalg.inv)...

[FALHA MATEMÁTICA DETECTADA]
Mensagem interna do Python: Singular matrix

Interpretação Econômica e Matemática:
O sistema bloqueou a operação porque a matriz A é singular (|A| = 0).
A dependência linear torna a matriz não inversível.
Consequentemente, é impossível calcular x = A^(-1)d para este modelo.


**Prova01_beta (matutino)**

Considere o sistema de equações lineares abaixo e responda:

$$
\begin{cases}
3x_1 + x_2 + 2x_3 = 3 \\
x_1 - 2x_2 + x_3 = -4 \\
2x_1 + 3x_2 - x_3 = 9
\end{cases}
$$

Este sistema linear pode representar o comportamento de um modelo econômico estrutural, como a relação de equilíbrio simultâneo entre produto, taxa de juros e taxa de câmbio.

**1)** Apresente o sistema de equações lineares no formato matricial $Ax=d$. Em seguida, calcule o determinante por meio da **expansão de Laplace** e discuta a existência de uma solução única e determinada para o sistema.

**2)** Obtenha a matriz inversa $A^{-1}$, considerando que $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$.

**3)** Quais são os componentes do vetor $x$? Utilize a regra de Cramer e demonstre que essa é a solução única do sistema.

**4)** Diante de um choque exógeno que altera as relações lineares, o modelo passa a responder à nova configuração:

$$
\begin{cases}
3x_1 + x_2 + 2x_3 = 7 \\
x_1 - 2x_2 + x_3 = 0 \\
4x_1 - x_2 + 3x_3 = 7
\end{cases}
$$

Esse sistema possui solução única? Justifique e demonstre por meio do determinante $|A|$ e das implicações na relação $x = A^{-1}d$.

**Obs.:** Responda às discussões teóricas com o devido rigor matemático e apresente detalhadamente o passo a passo para a resolução dos modelos formais.

**RESOLUÇÃO: Prova01_beta**

NSegue o mesmo roteiro de resolução da Prova 01 Alpha. No entanto, destacamos as diferenças:

* Os sistemas lineares analisados são distintos.
* As questões 1, 2 e 3 mantêm o mesmo roteiro e a mesma lógica matemática de resolução.
* A questão 4 apresenta um sistema impossível, pois existe inconsistência entre as equações.

**Questões 1, 2 e 3**

A mesma lógica de resolução da prova alpha. Apresento apenas os códigos e resultados

**1) Representação matricial, Expansão de Laplace e Solução Única**

A representação do modelo econômico no formato $Ax = d$ possui a seguinte estrutura:

$$ 
\begin{bmatrix} 
3 & 1 & 2 \\ 
1 & -2 & 1 \\ 
2 & 3 & -1 
\end{bmatrix} 
\begin{bmatrix} 
x_1 \\ 
x_2 \\ 
x_3 
\end{bmatrix} 
= 
\begin{bmatrix} 
3 \\ 
-4 \\ 
9 
\end{bmatrix} 
$$

Para calcular o determinante, nós aplicamos a expansão de Laplace ao longo da primeira linha da matriz de coeficientes $A$:

$$|A| = 3 \begin{vmatrix} -2 & 1 \\ 3 & -1 \end{vmatrix} - 1 \begin{vmatrix} 1 & 1 \\ 2 & -1 \end{vmatrix} + 2 \begin{vmatrix} 1 & -2 \\ 2 & 3 \end{vmatrix}$$

Nós resolvemos os determinantes dos menores principais:
$$|A| = 3(2 - 3) - 1(-1 - 2) + 2(3 - (-4))$$
$$|A| = 3(-1) - 1(-3) + 2(7)$$
$$|A| = -3 + 3 + 14 = 14$$

Como o determinante resulta em um valor diferente de zero ($|A| = 14 \neq 0$), nós confirmamos matematicamente que a matriz $A$ possui posto completo. Isso atesta que o sistema linear admite uma solução única e perfeitamente determinada para o modelo econômico.

**2) Matriz Inversa ($A^{-1}$)**

Para obter a matriz inversa, nós primeiro calculamos a matriz de cofatores $C$, transpomos para encontrar a adjunta e multiplicamos pelo inverso do determinante:

$$
C = \begin{bmatrix} 
-1 & 3 & 7 \\ 
7 & -7 & -7 \\ 
5 & -1 & -7 
\end{bmatrix}
$$

$$
\operatorname{adj} A = C^T = \begin{bmatrix} 
-1 & 7 & 5 \\ 
3 & -7 & -1 \\ 
7 & -7 & -7 
\end{bmatrix}
$$

Nós aplicamos a fórmula $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$:

$$
A^{-1} = \frac{1}{14} \begin{bmatrix} 
-1 & 7 & 5 \\ 
3 & -7 & -1 \\ 
7 & -7 & -7 
\end{bmatrix}
= \begin{bmatrix} 
-\frac{1}{14} & \frac{1}{2} & \frac{5}{14} \\ 
\frac{3}{14} & -\frac{1}{2} & -\frac{1}{14} \\ 
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} 
\end{bmatrix}
$$

**3) Vetor de soluções (Regra de Cramer) e Prova**

Nós calculamos os determinantes das matrizes modificadas substituindo as respectivas colunas pelo vetor $d$:
*   $|A_1| = 14$
*   $|A_2| = 28$
*   $|A_3| = -14$

Nós aplicamos a regra de Cramer ($x_j = \frac{|A_j|}{|A|}$) para extrair os componentes:
*   $x_1 = \frac{14}{14} = 1$
*   $x_2 = \frac{28}{14} = 2$
*   $x_3 = \frac{-14}{14} = -1$

O vetor de soluções é $x = \begin{bmatrix} 1 \\ 2 \\ -1 \end{bmatrix}$. 

Para provar que essa é a solução única, nós realizamos a substituição matricial na relação estrutural $Ax = d$:
$$ \begin{bmatrix} 3 & 1 & 2 \\ 1 & -2 & 1 \\ 2 & 3 & -1 \end{bmatrix} \begin{bmatrix} 1 \\ 2 \\ -1 \end{bmatrix} = \begin{bmatrix} 3(1) + 1(2) + 2(-1) \\ 1(1) - 2(2) + 1(-1) \\ 2(1) + 3(2) - 1(-1) \end{bmatrix} = \begin{bmatrix} 3 \\ -4 \\ 9 \end{bmatrix} $$

A substituição reproduz perfeitamente o vetor de constantes original.

In [20]:
# Carregar pacotes

import numpy as np
import sympy as sp

In [21]:
# Questões 1, 2 e 3

print("=== 1. Representação Matricial e Determinante ===")
A_np = np.array([
    [3, 1, 2],
    [1, -2, 1],
    [2, 3, -1]
])
d_np = np.array([3, -4, 9])

det_A = round(np.linalg.det(A_np))
print("Matriz A:\n", A_np)
print(f"Vetor d:\n {d_np}")
print(f"Determinante |A| (Expansão de Laplace) = {det_A}")
if det_A != 0:
    print("Conclusão: O determinante é não nulo. O modelo admite solução única.\n")

print("=== 2. Matriz Inversa (A^-1) ===")
n = A_np.shape[0]
C_np = np.zeros((n, n), dtype=int)

# Cálculo estruturado da Matriz de Cofatores
for i in range(n):
    for j in range(n):
        submatrix = np.delete(np.delete(A_np, i, axis=0), j, axis=1)
        minor_det = int(round(np.linalg.det(submatrix)))
        C_np[i, j] = ((-1) ** (i + j)) * minor_det

# Matriz Adjunta
adj_A_np = C_np.T

# Inversa via SymPy para exibir frações exatas
adj_A_sym = sp.Matrix(adj_A_np)
A_inv_sym = (1 / sp.Integer(det_A)) * adj_A_sym

print("Matriz Adjunta adj(A) = C^T:")
print(adj_A_np)
print("\nMatriz Inversa A^(-1):")
sp.pprint(A_inv_sym)
print("\n")

print("=== 3. Regra de Cramer e Prova ===")
x_sol = []
for j in range(n):
    A_j = A_np.copy()
    A_j[:, j] = d_np
    det_Aj = round(np.linalg.det(A_j))
    x_j = det_Aj / det_A
    x_sol.append(x_j)
    print(f"|A_{j+1}| = {det_Aj}  =>  x_{j+1} = {det_Aj}/{det_A} = {int(x_j)}")

x_vetor = np.array(x_sol, dtype=int)
print(f"\nVetor de soluções x: {x_vetor}")

# Prova
d_calculado = A_np @ x_vetor
print(f"Prova Ax = d: \n{A_np} @ {x_vetor} = {d_calculado}")
if np.array_equal(d_calculado, d_np):
    print("A igualdade é verdadeira. A solução única foi confirmada matematicamente.")


=== 1. Representação Matricial e Determinante ===
Matriz A:
 [[ 3  1  2]
 [ 1 -2  1]
 [ 2  3 -1]]
Vetor d:
 [ 3 -4  9]
Determinante |A| (Expansão de Laplace) = 14
Conclusão: O determinante é não nulo. O modelo admite solução única.

=== 2. Matriz Inversa (A^-1) ===
Matriz Adjunta adj(A) = C^T:
[[-1  7  5]
 [ 3 -7 -1]
 [ 7 -7 -7]]

Matriz Inversa A^(-1):
⎡-1/14  1/2   5/14 ⎤
⎢                  ⎥
⎢3/14   -1/2  -1/14⎥
⎢                  ⎥
⎣ 1/2   -1/2  -1/2 ⎦


=== 3. Regra de Cramer e Prova ===
|A_1| = 14  =>  x_1 = 14/14 = 1
|A_2| = 28  =>  x_2 = 28/14 = 2
|A_3| = -14  =>  x_3 = -14/14 = -1

Vetor de soluções x: [ 1  2 -1]
Prova Ax = d: 
[[ 3  1  2]
 [ 1 -2  1]
 [ 2  3 -1]] @ [ 1  2 -1] = [ 3 -4  9]
A igualdade é verdadeira. A solução única foi confirmada matematicamente.


**Questão 4)** 

O sistema não possui solução única. A matriz de coeficientes $A$ apresenta dependência linear, pois a terceira equação equivale à soma exata da primeira com a segunda ($L_3 = L_1 + L_2$). Como consequência direta dessa dependência, o determinante resulta em zero ($|A| = 0$).

Na relação matricial $x = A^{-1}d$, a condição $|A| = 0$ torna a matriz $A$ singular e não inversível, o que inviabiliza o cálculo estrutural por meio da inversa. No entanto, o vetor de constantes $d$ preserva a coerência matemática da mesma combinação linear ($7 + 0 = 7$). Por esse motivo, o sistema é classificado como possível e indeterminado, e admite infinitas soluções em vez de representar um sistema impossível.

In [22]:
# Questão 4

# 1. Definição da matriz de coeficientes (A) e do vetor de constantes (d)
A = np.array([
    [3, 1, 2],
    [1, -2, 1],
    [4, -1, 3]
])
d = np.array([7, 0, 7])

print("=== 1. Análise do Determinante ===")
# Cálculo do determinante com arredondamento para evitar ruídos de máquina
det_A = round(np.linalg.det(A))
print(f"Valor do determinante |A|: {det_A}")

if np.isclose(det_A, 0):
    print("O determinante resulta igual a zero. A matriz A apresenta dependência linear (L3 = L1 + L2).")
    print("O sistema não possui solução única.")

print("\n=== 2. Implicações na Relação x = A^(-1)d ===")
try:
    # O algoritmo tenta calcular a matriz inversa
    print("Iniciando o cálculo da inversa de A...")
    A_inv = np.linalg.inv(A)
    x = A_inv @ d
    print("Vetor de soluções:", x)
except np.linalg.LinAlgError as erro:
    # Captura estrutural da falha matemática
    print("[FALHA MATEMÁTICA DETECTADA]")
    print(f"Mensagem do Python: {erro}")
    print("Interpretação: Como |A| = 0, a matriz A é singular e não inversível.")
    print("A dependência linear impõe uma divisão por zero na fórmula da matriz inversa.")
    print("Isso inviabiliza completamente a utilização do método x = A^(-1)d.")

print("\n=== 3. Diagnóstico Estrutural do Modelo ===")
# Verificação do posto matricial (rank) para classificar o sistema
posto_A = np.linalg.matrix_rank(A)
matriz_aumentada = np.column_stack((A, d))
posto_aumentada = np.linalg.matrix_rank(matriz_aumentada)

print(f"Posto da matriz A: {posto_A}")
print(f"Posto da matriz aumentada [A|d]: {posto_aumentada}")
print(f"Número de variáveis do modelo: {A.shape[1]}")

if posto_A == posto_aumentada and posto_A < A.shape[1]:
    print("\nConclusão Final: O vetor d preserva a mesma coerência linear das linhas (7 + 0 = 7).")
    print("O sistema é possível e indeterminado, logo, admite infinitas soluções.")

=== 1. Análise do Determinante ===
Valor do determinante |A|: 0
O determinante resulta igual a zero. A matriz A apresenta dependência linear (L3 = L1 + L2).
O sistema não possui solução única.

=== 2. Implicações na Relação x = A^(-1)d ===
Iniciando o cálculo da inversa de A...
[FALHA MATEMÁTICA DETECTADA]
Mensagem do Python: Singular matrix
Interpretação: Como |A| = 0, a matriz A é singular e não inversível.
A dependência linear impõe uma divisão por zero na fórmula da matriz inversa.
Isso inviabiliza completamente a utilização do método x = A^(-1)d.

=== 3. Diagnóstico Estrutural do Modelo ===
Posto da matriz A: 2
Posto da matriz aumentada [A|d]: 2
Número de variáveis do modelo: 3

Conclusão Final: O vetor d preserva a mesma coerência linear das linhas (7 + 0 = 7).
O sistema é possível e indeterminado, logo, admite infinitas soluções.


**Prova01_tau (substitutiva)**


Considere o sistema de equações lineares abaixo e responda:

$$
\begin{cases}
x_1 + 2x_2 + x_3 = 5 \\
2x_1 - x_2 + 3x_3 = -3 \\
x_1 + x_2 - 2x_3 = 6
\end{cases}
$$

Este sistema linear pode representar o comportamento de um modelo econômico estrutural, como a relação de equilíbrio simultâneo entre produto, taxa de juros e taxa de câmbio.

**1)** Apresente o sistema de equações lineares no formato matricial $Ax=d$. Em seguida, calcule o determinante por meio da **expansão de Laplace** e discuta a existência de uma solução única e determinada para o sistema.

**2)** Obtenha a matriz inversa $A^{-1}$, considerando que $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$.

**3)** Quais são os componentes do vetor $x$? Utilize a regra de Cramer e demonstre que essa é a solução única do sistema.

**4)** Diante de um choque exógeno que altera as relações lineares, o modelo passa a responder à nova configuração:

$$
\begin{cases}
x_1 + 2x_2 + x_3 = 5 \\
2x_1 - x_2 + 3x_3 = -3 \\
3x_1 + x_2 + 4x_3 = 2
\end{cases}
$$

Esse sistema possui solução única? Justifique e demonstre por meio do determinante $|A|$ e das implicações na relação $x = A^{-1}d$.

**Obs.:** Responda às discussões teóricas com o devido rigor matemático e apresente detalhadamente o passo a passo para a resolução dos modelos formais.

**RESOLUÇÃO: Prova01_tau**

A prova01 tau é similar a prova beta, mas com sistemas lineares diferentes.


**Resolução prova01_tau**

### Resolução Analítica: Prova Tau

**1) Representação matricial, Expansão de Laplace e Solução Única**

A representação do modelo econômico no formato $Ax = d$ possui a seguinte estrutura:

$$ 
\begin{bmatrix} 
1 & 2 & 1 \\ 
2 & -1 & 3 \\ 
1 & 1 & -2 
\end{bmatrix} 
\begin{bmatrix} 
x_1 \\ 
x_2 \\ 
x_3 
\end{bmatrix} 
= 
\begin{bmatrix} 
5 \\ 
-3 \\ 
6 
\end{bmatrix} 
$$

Para calcular o determinante, nós aplicamos a expansão de Laplace ao longo da primeira linha da matriz de coeficientes $A$:

$$|A| = 1 \begin{vmatrix} -1 & 3 \\ 1 & -2 \end{vmatrix} - 2 \begin{vmatrix} 2 & 3 \\ 1 & -2 \end{vmatrix} + 1 \begin{vmatrix} 2 & -1 \\ 1 & 1 \end{vmatrix}$$

Nós resolvemos os determinantes dos menores principais:
$$|A| = 1(2 - 3) - 2(-4 - 3) + 1(2 - (-1))$$
$$|A| = 1(-1) - 2(-7) + 1(3)$$
$$|A| = -1 + 14 + 3 = 16$$

Como o determinante resulta em um valor diferente de zero ($|A| = 16 \neq 0$), nós confirmamos matematicamente que a matriz $A$ possui posto completo. Isso atesta que o sistema linear admite uma solução única e perfeitamente determinada para o modelo econômico.

**2) Matriz Inversa ($A^{-1}$)**

Para obter a matriz inversa, nós primeiro calculamos a matriz de cofatores $C$, transpomos para encontrar a adjunta e multiplicamos pelo inverso do determinante:

$$
C = \begin{bmatrix} 
-1 & 7 & 3 \\ 
5 & -3 & 1 \\ 
7 & -1 & -5 
\end{bmatrix}
$$

$$
\operatorname{adj} A = C^T = \begin{bmatrix} 
-1 & 5 & 7 \\ 
7 & -3 & -1 \\ 
3 & 1 & -5 
\end{bmatrix}
$$

Nós aplicamos a fórmula $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$:

$$
A^{-1} = \frac{1}{16} \begin{bmatrix} 
-1 & 5 & 7 \\ 
7 & -3 & -1 \\ 
3 & 1 & -5 
\end{bmatrix}
= \begin{bmatrix} 
-\frac{1}{16} & \frac{5}{16} & \frac{7}{16} \\ 
\frac{7}{16} & -\frac{3}{16} & -\frac{1}{16} \\ 
\frac{3}{16} & \frac{1}{16} & -\frac{5}{16} 
\end{bmatrix}
$$

**3) Vetor de soluções (Regra de Cramer) e Prova**

Nós calculamos os determinantes das matrizes modificadas substituindo as respectivas colunas pelo vetor $d$:
*   $|A_1| = \begin{vmatrix} 5 & 2 & 1 \\ -3 & -1 & 3 \\ 6 & 1 & -2 \end{vmatrix} = 5(-1) - 2(-12) + 1(3) = -5 + 24 + 3 = 22$
*   $|A_2| = \begin{vmatrix} 1 & 5 & 1 \\ 2 & -3 & 3 \\ 1 & 6 & -2 \end{vmatrix} = 1(-12) - 5(-7) + 1(15) = -12 + 35 + 15 = 38$
*   $|A_3| = \begin{vmatrix} 1 & 2 & 5 \\ 2 & -1 & -3 \\ 1 & 1 & 6 \end{vmatrix} = 1(-3) - 2(15) + 5(3) = -3 - 30 + 15 = -18$

Nós aplicamos a regra de Cramer ($x_j = \frac{|A_j|}{|A|}$) para extrair os componentes:
*   $x_1 = \frac{22}{16} = \frac{11}{8}$
*   $x_2 = \frac{38}{16} = \frac{19}{8}$
*   $x_3 = -\frac{18}{16} = -\frac{9}{8}$

O vetor exato de soluções é $x = \begin{bmatrix} 11/8 \\ 19/8 \\ -9/8 \end{bmatrix}$. 

Para provar que essa é a solução única, nós realizamos a substituição matricial na relação estrutural $Ax = d$:
$$ \begin{bmatrix} 1 & 2 & 1 \\ 2 & -1 & 3 \\ 1 & 1 & -2 \end{bmatrix} \begin{bmatrix} 11/8 \\ 19/8 \\ -9/8 \end{bmatrix} = \begin{bmatrix} 1(11/8) + 2(19/8) + 1(-9/8) \\ 2(11/8) - 1(19/8) + 3(-9/8) \\ 1(11/8) + 1(19/8) - 2(-9/8) \end{bmatrix} = \begin{bmatrix} 40/8 \\ -24/8 \\ 48/8 \end{bmatrix} = \begin{bmatrix} 5 \\ -3 \\ 6 \end{bmatrix} $$

A substituição reproduz perfeitamente o vetor de constantes original.

**4) Choque exógeno e Análise da Solução Única**

O novo sistema não possui solução única. A matriz de coeficientes $A$ alterada apresenta dependência linear, visto que a terceira equação equivale à soma exata da primeira com a segunda ($L_3 = L_1 + L_2$). Como consequência direta dessa dependência estrutural, o determinante resulta em zero ($|A| = 0$).

Na relação matricial $x = A^{-1}d$, a condição $|A| = 0$ torna a matriz $A$ singular e não inversível, o que inviabiliza o cálculo estrutural por meio da matriz inversa devido a uma divisão por zero na fórmula. 

No entanto, o novo vetor de constantes $d$ preserva a coerência matemática da mesma combinação linear exata verificada nas linhas ($5 + (-3) = 2$). Por esse motivo, classificamos o modelo atualizado como um sistema possível e indeterminado, o qual admite infinitas soluções.

In [23]:
# Carregar pacotes

import numpy as np
import sympy as sp

In [25]:
# Resolução prova01_tau


print("=== PARTE 1: Sistema Original (Questões 1, 2 e 3) ===")

# Definição da matriz A e do vetor d
A_np = np.array([
    [1, 2, 1],
    [2, -1, 3],
    [1, 1, -2]
])
d_np = np.array([5, -3, 6])

# 1. Cálculo do Determinante
det_A = round(np.linalg.det(A_np))
print(f"Determinante |A| = {det_A}")
if det_A != 0:
    print("Conclusão: A matriz possui posto completo. O sistema admite solução única.\n")

# 2. Cálculo da Matriz Inversa
n = A_np.shape[0]
C_np = np.zeros((n, n), dtype=int)

# Construção da matriz de cofatores
for i in range(n):
    for j in range(n):
        submatrix = np.delete(np.delete(A_np, i, axis=0), j, axis=1)
        minor_det = int(round(np.linalg.det(submatrix)))
        C_np[i, j] = ((-1) ** (i + j)) * minor_det

adj_A_np = C_np.T
adj_A_sym = sp.Matrix(adj_A_np)
A_inv_sym = (1 / sp.Integer(det_A)) * adj_A_sym

print("Matriz Adjunta adj(A) = C^T:")
print(adj_A_np)
print("\nMatriz Inversa A^(-1) com frações exatas:")
sp.pprint(A_inv_sym)

# 3. Regra de Cramer e Prova
print("\n=== Regra de Cramer ===")
x_sol = []
for j in range(n):
    A_j = A_np.copy()
    A_j[:, j] = d_np
    det_Aj = round(np.linalg.det(A_j))
    x_j = det_Aj / det_A
    x_sol.append(x_j)
    print(f"|A_{j+1}| = {det_Aj}  =>  x_{j+1} = {det_Aj}/{det_A} = {x_j}")

x_vetor = np.array(x_sol)
print(f"\nVetor exato de soluções x:\n{x_vetor}")

# Verificação da igualdade Ax = d
d_calculado = A_np @ x_vetor
print(f"\nProva Ax = d: \n{d_calculado}")
if np.allclose(d_calculado, d_np):
    print("A igualdade é verdadeira. A solução foi validada com sucesso.\n")


print("\n=== PARTE 2: Choque Exógeno (Questão 4) ===")

# Definição do novo modelo após o choque
A_choque = np.array([
    [1, 2, 1],
    [2, -1, 3],
    [3, 1, 4]
])
d_choque = np.array([5, -3, 2])

# Análise do novo determinante
det_choque = round(np.linalg.det(A_choque))
print(f"Novo determinante |A| = {det_choque}")

if np.isclose(det_choque, 0):
    print("O determinante resulta em zero. A nova matriz apresenta dependência linear (L3 = L1 + L2).")

print("\nTentativa de inversão matricial x = A^(-1)d:")
try:
    A_choque_inv = np.linalg.inv(A_choque)
    x_choque = A_choque_inv @ d_choque
except np.linalg.LinAlgError as erro:
    print("[FALHA MATEMÁTICA DETECTADA]")
    print(f"Mensagem do Python: {erro}")
    print("Interpretação: A matriz singular impede a inversão devido a uma divisão por zero estrutural.")

# Diagnóstico de Posto (Rank)
posto_A_choque = np.linalg.matrix_rank(A_choque)
matriz_aumentada_choque = np.column_stack((A_choque, d_choque))
posto_aumentada_choque = np.linalg.matrix_rank(matriz_aumentada_choque)

if posto_A_choque == posto_aumentada_choque and posto_A_choque < A_choque.shape[1]:
    print("\nConclusão Estrutural:")
    print("Os postos da matriz de coeficientes e da matriz aumentada são iguais, mas menores que o número de variáveis.")
    print("Isso prova que o sistema é possível e indeterminado, admitindo infinitas soluções.")

=== PARTE 1: Sistema Original (Questões 1, 2 e 3) ===
Determinante |A| = 16
Conclusão: A matriz possui posto completo. O sistema admite solução única.

Matriz Adjunta adj(A) = C^T:
[[-1  5  7]
 [ 7 -3 -1]
 [ 3  1 -5]]

Matriz Inversa A^(-1) com frações exatas:
⎡-1/16  5/16   7/16 ⎤
⎢                   ⎥
⎢7/16   -3/16  -1/16⎥
⎢                   ⎥
⎣3/16   1/16   -5/16⎦

=== Regra de Cramer ===
|A_1| = 22  =>  x_1 = 22/16 = 1.375
|A_2| = 38  =>  x_2 = 38/16 = 2.375
|A_3| = -18  =>  x_3 = -18/16 = -1.125

Vetor exato de soluções x:
[ 1.375  2.375 -1.125]

Prova Ax = d: 
[ 5. -3.  6.]
A igualdade é verdadeira. A solução foi validada com sucesso.


=== PARTE 2: Choque Exógeno (Questão 4) ===
Novo determinante |A| = 0
O determinante resulta em zero. A nova matriz apresenta dependência linear (L3 = L1 + L2).

Tentativa de inversão matricial x = A^(-1)d:

Conclusão Estrutural:
Os postos da matriz de coeficientes e da matriz aumentada são iguais, mas menores que o número de variáveis.
Isso prov

### IMPORTANTE!!!!

A resolução por meio do Python tem como objetivo apresentar o uso da economia computacional aplicado aos problemas de economia matemática. Essa prática não substitui o conhecimento das regras e rotinas analíticas necessárias para a álgebra linear, embora constitua um instrumento útil para identificar os efeitos de mudanças de parâmetros e suas respectivas implicações.