Universidade Federal do ABC (UFABC)  
Curso: Bacharelado em Ciências Econômicas  
Disciplina: Economia Matemática  
Período: 2º Quadrimestre de 2026  
Turmas: Matutino (DA2ESHC027-21SB) e Noturno (NA2ESHC027-21SB)  
Lista de Exercícios: Lista 2 (Aulas 2 a 11) | Entrega: 24 de julho de 2026 (sexta-feira) 
  
Prof. Dr. Elson Rodrigo de Souza Santos  
WhatsApp: (41) 9 8454 0549 | E-mail: elson129@gmail.com ou elson.rodrigo@ufabc.edu.br | Repositório: github.com/elsonr29  
18 de julho de 2026  

RESOLUÇÃO DA LISTA I

Observações:
    
1) Utilizamos o Python e os fundamentos da "quantitative economics", aula 8 - Linear Equations and Matrix Algebra < https://intro.quantecon.org/linear_equations.html > ;   
2) Os resultados devem ser coerentes com os obtidos manualmente; 
3) O Python é uma forma inclusiva de demonstrar os conceitos e modelos apresentados e discutidos em sala de aula;  
4) A ênfase é a parte quantitativa da lista de exercícios. 

In [54]:
# Pacotes

# Instação (se necessário)

!pip install numpy sympy

#Obs.: Utilizamos o numpy para manipulação de matrizes e álgebra e o matplotlib para formatação de gráficos. Seguimos o caminho proposto pela Quantitative Economics.


[notice] A new release of pip is available: 25.3 -> 26.2
[notice] To update, run: pip install --upgrade pip


In [55]:
# Carregamento

import numpy as np  
import sympy as sp

# Obs.: após o carregamento é possível resolver a lista.

A partir do sistema de equações lineares abaixo, responda:

\begin{equation}
	\begin{cases}
		x_1 + 2x_2 + x_3 = 3 \\
		3x_1 - x_2 - x_3 = 10 \\
		x_1 + 3x_2 + 2x_3 = 2
	\end{cases}
\end{equation}

1) Calcule o determinante da matriz $A$ a partir da **expansão de Laplace**. Interprete o resultado obtido em relação à existência de uma solução única para o sistema linear.


In [56]:
# carregar pacotes

import numpy as np
import sympy as sp

In [57]:

# a) transformamos o sistema de equaçoes lineares para matricial na notação Ax = d

# matriz A como matriz quadrada (3 x 3)

A_np = np.array([
    [1,  2,  1],
    [3, -1, -1],
    [1,  3,  2]
])

d_np = np.array([3, 10, 2])

# Trasnformamos de np para sym

A_sym = sp.Matrix(A_np)
d_sym = sp.Matrix(d_np)

# matriz x como vetor coluna (3 x 1)

x1, x2, x3 = sp.symbols('x1 x2 x3')
x_sym = sp.Matrix([[x1], 
                   [x2], 
                   [x3]])


print("Relação Matricial Ax = d")

print("Matriz A:")
print(A_np)

print("\nVetor de variáveis x:")
print(x_sym)

print("\nVetor d:")
print(d_sym)

# Relação Ax=d

print("\nAx = d:")

sp.pprint(sp.Eq(sp.MatMul(A_sym, x_sym, evaluate=False), d_sym))

print("-" * 50)

Relação Matricial Ax = d
Matriz A:
[[ 1  2  1]
 [ 3 -1 -1]
 [ 1  3  2]]

Vetor de variáveis x:
Matrix([[x1], [x2], [x3]])

Vetor d:
Matrix([[3], [10], [2]])

Ax = d:
⎡1  2   1 ⎤ ⎡x₁⎤   ⎡3 ⎤
⎢         ⎥ ⎢  ⎥   ⎢  ⎥
⎢3  -1  -1⎥⋅⎢x₂⎥ = ⎢10⎥
⎢         ⎥ ⎢  ⎥   ⎢  ⎥
⎣1  3   2 ⎦ ⎣x₃⎦   ⎣2 ⎦
--------------------------------------------------


In [58]:
# b) Determinante da matriz A pela expansão de Laplace

# usamos a expansão da primeira linha

def laplace_expansion_first_row(matrix):
    
    n = matrix.shape[0]
    det = 0
    print("\nExpansão de Laplace na Primeira Linha")
    
    for j in range(n):
        element = matrix[0, j]
        
        # Submatriz ignorando a linha 0 e a coluna j
        submatrix = np.delete(np.delete(matrix, 0, axis=0), j, axis=1)
        
        # Determinante do menor principal (2x2)
        minor_det = np.linalg.det(submatrix)
        
        # Cofactor C_{0, j} = (-1)^(0 + j) * M_{0, j}
        cofactor = ((-1) ** (0 + j)) * minor_det
        
        term = element * cofactor
        det += term
        
        print(f"\nElemento a_1{j+1} = {element}")
        print(f"Submatriz M_1{j+1}:\n{submatrix}")
        print(f"Cofactor C_1{j+1} = (-1)^(1+{j+1}) * det(M_1{j+1}) = {cofactor:.1f}")
        print(f"Termo {j+1}: {element} * ({cofactor:.1f}) = {term:.1f}")
        
    return int(round(det))

# executa a expansão de Laplace

det_A = laplace_expansion_first_row(A_np)

print(f"Determinante da Matriz A via Laplace: det(A) = {det_A}")



Expansão de Laplace na Primeira Linha

Elemento a_11 = 1
Submatriz M_11:
[[-1 -1]
 [ 3  2]]
Cofactor C_11 = (-1)^(1+1) * det(M_11) = 1.0
Termo 1: 1 * (1.0) = 1.0

Elemento a_12 = 2
Submatriz M_12:
[[ 3 -1]
 [ 1  2]]
Cofactor C_12 = (-1)^(1+2) * det(M_12) = -7.0
Termo 2: 2 * (-7.0) = -14.0

Elemento a_13 = 1
Submatriz M_13:
[[ 3 -1]
 [ 1  3]]
Cofactor C_13 = (-1)^(1+3) * det(M_13) = 10.0
Termo 3: 1 * (10.0) = 10.0
Determinante da Matriz A via Laplace: det(A) = -3


In [59]:
# c) veriicar se há solução

A_sym = sp.Matrix([
    [1,  2,  1],
    [3, -1, -1],
    [1,  3,  2]
])
d_sym = sp.Matrix([3, 10, 2])

# Determinante exato
det_exact = A_sym.det()

print("\nVerificação Exata (SymPy)")
print(f"det(A) = {det_exact}")
if det_exact != 0:
    print(f"O sistema é Possível e Determinado (SPD).")


Verificação Exata (SymPy)
det(A) = -3
O sistema é Possível e Determinado (SPD).


2) Encontre a matriz inversa $A^{-1}$, utilizando a relação $A^{-1} = \frac{1}{|A|} \operatorname{adj} A$.

In [60]:
# carregar pacotes

import numpy as np
import sympy as sp

In [61]:
# Resultado da determinante da matriz A da questão anterior

# Matriz A original e determinante |A| = -3
A_np = np.array([
    [1,  2,  1],
    [3, -1, -1],
    [1,  3,  2]
])

det_A = -3

In [62]:
# a) matriz de cofatores C

n = A_np.shape[0]
C_np = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        # Remove a linha i e a coluna j para obter a submatriz
        submatrix = np.delete(np.delete(A_np, i, axis=0), j, axis=1)
        # Menor principal M_ij
        minor_det = int(round(np.linalg.det(submatrix)))
        # Cofactor C_ij = (-1)^(i+j) * M_ij
        C_np[i, j] = ((-1) ** (i + j)) * minor_det

print("a) Matriz de Cofactores C:")
print(C_np)
print()

# Obs. automatizamos o processo para construção da matriz de cofatores

a) Matriz de Cofactores C:
[[ 1 -7 10]
 [-1  1 -1]
 [-1  4 -7]]



In [63]:
# b) Transposta da matriz C para encontrar a matriz adjunta adj(A)

adj_A_np = C_np.T

print("b) Matriz Adjunta adj(A) = C^T:")
print(adj_A_np)
print()

b) Matriz Adjunta adj(A) = C^T:
[[ 1 -1 -1]
 [-7  1  4]
 [10 -1 -7]]



In [64]:
# c) Matriz inversa

adj_A_sym = sp.Matrix(adj_A_np)
A_inv_sym = (1 / sp.Integer(det_A)) * adj_A_sym

print("c) Matriz Inversa A^(-1):")
sp.pprint(A_inv_sym)
print()

c) Matriz Inversa A^(-1):
⎡-1/3   1/3   1/3 ⎤
⎢                 ⎥
⎢ 7/3   -1/3  -4/3⎥
⎢                 ⎥
⎣-10/3  1/3   7/3 ⎦



In [65]:
# d) Prova que A * A⁽-1) = I

A_sym = sp.Matrix(A_np)

print("d) Prova: A * A^(-1) = I:")

sp.pprint(
    sp.Eq(
        sp.MatMul(A_sym, A_inv_sym, evaluate=False),
        A_sym * A_inv_sym
    )
)

print("\n" + "-" * 50)

# Obs. automatizamos o processo pelos pacotes

d) Prova: A * A^(-1) = I:
⎡1  2   1 ⎤ ⎡-1/3   1/3   1/3 ⎤   ⎡1  0  0⎤
⎢         ⎥ ⎢                 ⎥   ⎢       ⎥
⎢3  -1  -1⎥⋅⎢ 7/3   -1/3  -4/3⎥ = ⎢0  1  0⎥
⎢         ⎥ ⎢                 ⎥   ⎢       ⎥
⎣1  3   2 ⎦ ⎣-10/3  1/3   7/3 ⎦   ⎣0  0  1⎦

--------------------------------------------------


3) Encontre os valores das variáveis do vetor $x$ a partir da Regra de Cramer.

In [66]:
# Carregar pacotes

import numpy as np
import sympy as sp

In [67]:
# a) definir matriz A e vetor de resultados d

A_np = np.array([
    [1,  2,  1],
    [3, -1, -1],
    [1,  3,  2]
])

d_np = np.array([3, 10, 2])

det_A = -3

# Obs. obtivemos nas etapas anteriores

In [68]:
# b) Armazenas as soluções

x_sol = []
x_vars = ['x1', 'x2', 'x3']

for j in range(3):
    # Cria uma cópia da matriz A e substitui a coluna j pelo vetor d
    A_j = A_np.copy()
    A_j[:, j] = d_np
    
    # Cálculo do determinante da matriz A_j
    det_A_j = int(round(np.linalg.det(A_j)))
    
    # Aplicação da Regra de Cramer: x_j = det(A_j) / det(A)
    val_x_j = int(round(det_A_j / det_A))
    x_sol.append(val_x_j)
    
    print(f"Matriz A_{j+1} (substituindo coluna {j+1}):")
    print(A_j)
    print(f"det(A_{j+1}) = {det_A_j}")
    print(f"{x_vars[j]} = det(A_{j+1}) / det(A) = {det_A_j} / {det_A} = {val_x_j}\n")

Matriz A_1 (substituindo coluna 1):
[[ 3  2  1]
 [10 -1 -1]
 [ 2  3  2]]
det(A_1) = -9
x1 = det(A_1) / det(A) = -9 / -3 = 3

Matriz A_2 (substituindo coluna 2):
[[ 1  3  1]
 [ 3 10 -1]
 [ 1  2  2]]
det(A_2) = -3
x2 = det(A_2) / det(A) = -3 / -3 = 1

Matriz A_3 (substituindo coluna 3):
[[ 1  2  3]
 [ 3 -1 10]
 [ 1  3  2]]
det(A_3) = 6
x3 = det(A_3) / det(A) = 6 / -3 = -2



In [69]:
# c) vetor final

x_sym = sp.Matrix(x_sol)

print("Vetor Solução x:")
sp.pprint(x_sym)

print("\n" + "-" * 50)

Vetor Solução x:
⎡3 ⎤
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎣-2⎦

--------------------------------------------------


4) Suponha que tenha ocorrido um choque exógeno no sistema, alterando a estrutura de relações para o novo sistema linear:

$$\begin{cases} x_1 + 2x_2 + x_3 = 3 \\ 3x_1 - x_2 - x_3 = 10 \\ 2x_1 + 4x_2 + 2x_3 = 6 \end{cases}$$

O novo sistema de equações possui solução única? Justifique a sua resposta de forma teórica e formal. Caso não possua, quais modificações seriam necessárias para que o sistema apresente uma solução única? Caso possua, identifique os valores do vetor $x$ por meio da Regra de Cramer.

In [70]:
# carregar o pacote

import numpy as np
import sympy as sp

In [71]:
# a) notação matricial

A_novo_np = np.array([
    [1,  2,  1],
    [3, -1, -1],
    [2,  4,  2]
])

# Vetor de termos independentes d_novo (3x1)
d_novo_np = np.array([3, 10, 6])

In [72]:
# b) Determinante na matriz pós-choque

A_novo_sym = sp.Matrix(A_novo_np)
det_A_novo = A_novo_sym.det()

print(f"1) Determinante da nova matriz de coeficientes:")
print(f"det(A_novo) = {det_A_novo}\n")

if det_A_novo == 0:
    print("Conclusão sobre unicidade:")
    print("Como det(A) = 0, a matriz A é SINGULAR (não invertível).")
    print("Pelo Teorema da Matriz Invertível / Rouché-Capelli, O SISTEMA NÃO POSSUI SOLUÇÃO ÚNICA.")
    print("O sistema é Indeterminado (infinitas soluções) ou Impossível (nenhuma solução).")
else:
    print("O sistema possui solução única (Possível e Determinado).")

print("\n" + "-" * 60 + "\n")


1) Determinante da nova matriz de coeficientes:
det(A_novo) = 0

Conclusão sobre unicidade:
Como det(A) = 0, a matriz A é SINGULAR (não invertível).
Pelo Teorema da Matriz Invertível / Rouché-Capelli, O SISTEMA NÃO POSSUI SOLUÇÃO ÚNICA.
O sistema é Indeterminado (infinitas soluções) ou Impossível (nenhuma solução).

------------------------------------------------------------



In [73]:
# b) identificar dependência linear

posto_A = A_novo_sym.rank()
n_variaveis = A_novo_sym.cols

print(f"Posto da matriz A (Rank): {posto_A}")
print(f"Número de variáveis: {n_variaveis}")
print(f"Como Rank(A) = {posto_A} < {n_variaveis}, as linhas/colunas são Linearmente Dependentes (LD).\n")

# Identificação a combinação das linhas

L1 = A_novo_sym.row(0)
L2 = A_novo_sym.row(1)
L3 = A_novo_sym.row(2)

print("Relação explícita entre as equações (linhas da matriz A):")
if L3 == 2 * L1:
    print("-> A Linha 3 é exatamente o dobro da Linha 1: L3 = 2 * L1")
    print("-> Matematicamente: 2*(1, 2, 1) = (2, 4, 2)")
    print("-> Equação 3: 2*x1 + 4*x2 + 2*x3 = 6  <=>  2*(x1 + 2*x2 + x3 = 3)")

Posto da matriz A (Rank): 2
Número de variáveis: 3
Como Rank(A) = 2 < 3, as linhas/colunas são Linearmente Dependentes (LD).

Relação explícita entre as equações (linhas da matriz A):
-> A Linha 3 é exatamente o dobro da Linha 1: L3 = 2 * L1
-> Matematicamente: 2*(1, 2, 1) = (2, 4, 2)
-> Equação 3: 2*x1 + 4*x2 + 2*x3 = 6  <=>  2*(x1 + 2*x2 + x3 = 3)


In [74]:
# c) classificação da matriz [A|d]

A_aumentada = A_novo_sym.row_join(sp.Matrix(d_novo_np))
posto_A_aumentada = A_aumentada.rank()

print(f"\nPosto da Matriz Aumentada [A|d]: {posto_A_aumentada}")
if posto_A == posto_A_aumentada:
    print("Como Rank(A) == Rank(A|d) = 2 < 3, o sistema é SISTEMA POSSÍVEL E INDETERMINADO (SPI).")
    print("A 3ª equação é redundante, gerando infinitas soluções.")
else:
    print("Como Rank(A) != Rank(A|d), o sistema é IMPOSSÍVEL (SI).")

print("\n" + "-" * 60)


Posto da Matriz Aumentada [A|d]: 2
Como Rank(A) == Rank(A|d) = 2 < 3, o sistema é SISTEMA POSSÍVEL E INDETERMINADO (SPI).
A 3ª equação é redundante, gerando infinitas soluções.

------------------------------------------------------------


5) Suponha que tenha ocorrido um novo choque exógeno no sistema, alterando a estrutura de parâmetros para a seguinte configuração linear:

$$\begin{cases} x_1 + 2x_2 + x_3 = 3 \\ 3x_1 - x_2 - x_3 = 5 \\ x_1 + x_2 + 4x_3 = 6 \end{cases}$$

O novo sistema de equações possui solução única? Justifique a sua resposta de forma teórica e formal. Caso não possua, quais modificações seriam necessárias para que o sistema apresente uma solução única? Caso possua, identifique os valores do vetor $x$ por meio da Regra de Cramer.

In [75]:
# Carregar pacotes

import numpy as np
import sympy as sp


In [76]:
# a) notação matricial

#Matriz de coeficientes A_5 (3x3)

A_5_np = np.array([
    [1,  2, 1],
    [3, -1, -1],
    [1,  1, 4]
])

# Vetor de termos independentes d_5 (3x1)
d_5_np = np.array([3, 5, 6])

In [77]:
# b) Determinante da matriz A pós-choque

A_5_sym = sp.Matrix([[1, 2, 1], [3, -1, -1], [1, 1, 4]])
det_A_5 = A_5_sym.det()

print("b) Determinante da matriz A pós-choque:")
print(f"det(A_5) = {det_A_5}\n")

if det_A_5 != 0:
    print("Conclusão sobre unicidade:")
    print(f"Como det(A) = {det_A_5} != 0, a matriz A é NÃO SINGULAR (invertível).")
    print("Pelo Teorema da Matriz Invertível / Rouché-Capelli, O SISTEMA POSSUI SOLUÇÃO ÚNICA (SPD).")
else:
    print("Como det(A) = 0, o sistema não possui solução única.")

print("\n" + "-" * 60 + "\n")

b) Determinante da matriz A pós-choque:
det(A_5) = -25

Conclusão sobre unicidade:
Como det(A) = -25 != 0, a matriz A é NÃO SINGULAR (invertível).
Pelo Teorema da Matriz Invertível / Rouché-Capelli, O SISTEMA POSSUI SOLUÇÃO ÚNICA (SPD).

------------------------------------------------------------



In [78]:
# c) independência linear

posto_A = A_5_sym.rank()
n_variaveis = A_5_sym.cols

print(f"Posto da matriz A (Rank): {posto_A}")
print(f"Número de variáveis: {n_variaveis}")
print(f"Como Rank(A) = {posto_A} == {n_variaveis}, os vetores linhas e colunas são LINEARMENTE INDEPENDENTES (LI).")
print("Não existem equações redundantes na estrutura de parâmetros.")

print("\n" + "-" * 60 + "\n")

Posto da matriz A (Rank): 3
Número de variáveis: 3
Como Rank(A) = 3 == 3, os vetores linhas e colunas são LINEARMENTE INDEPENDENTES (LI).
Não existem equações redundantes na estrutura de parâmetros.

------------------------------------------------------------



In [79]:
# d) Solução pela Regra de Cramer

x_sol = []
x_vars = ['x1', 'x2', 'x3']

for j in range(3):
    # Substitui a j-ésima coluna pelo vetor d
    A_j = A_5_np.copy()
    A_j[:, j] = d_5_np
    
    A_j_sym = sp.Matrix(A_j)
    det_A_j = A_j_sym.det()
    
    # x_j = det(A_j) / det(A)
    val_x_j = sp.Rational(det_A_j, det_A_5)
    x_sol.append(val_x_j)
    
    print(f"Matriz A_{j+1} (coluna {j+1} substituída por d):")
    sp.pprint(A_j_sym)
    print(f"det(A_{j+1}) = {det_A_j}")
    print(f"{x_vars[j]} = det(A_{j+1}) / det(A) = {det_A_j} / {det_A_5} = {val_x_j}\n")

#  Vetor Solução x

x_sym = sp.Matrix(x_sol)

print("Vetor Solução x:")
sp.pprint(x_sym)

print("\n" + "-" * 60)

Matriz A_1 (coluna 1 substituída por d):
⎡3  2   1 ⎤
⎢         ⎥
⎢5  -1  -1⎥
⎢         ⎥
⎣6  1   4 ⎦
det(A_1) = -50
x1 = det(A_1) / det(A) = -50 / -25 = 2

Matriz A_2 (coluna 2 substituída por d):
⎡1  3  1 ⎤
⎢        ⎥
⎢3  5  -1⎥
⎢        ⎥
⎣1  6  4 ⎦
det(A_2) = 0
x2 = det(A_2) / det(A) = 0 / -25 = 0

Matriz A_3 (coluna 3 substituída por d):
⎡1  2   3⎤
⎢        ⎥
⎢3  -1  5⎥
⎢        ⎥
⎣1  1   6⎦
det(A_3) = -25
x3 = det(A_3) / det(A) = -25 / -25 = 1

Vetor Solução x:
⎡2⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣1⎦

------------------------------------------------------------


A resolução por meio do Python tem como objetivo apresentar o uso da economia computacional aplicado aos problemas de economia matemática. Essa prática não substitui o conhecimento das regras e rotinas analíticas necessárias para a álgebra linear, embora constitua um instrumento útil para identificar os efeitos de mudanças de parâmetros e suas respectivas implicações.